name: "tivn_chart"
description: Dev by Thai Son - IT


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # json_annotation: ^4.7.0 
  # json_serializable: ^6.5.4 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons. 
  cupertino_icons: ^1.0.2
  # excel_dart: any
  path_provider: ^2.0.11 
  # device_info_plus: ^8.0.0 
  connect_to_sql_server_directly: ^0.0.1
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2
  syncfusion_flutter_charts: ^20.3.61
  syncfusion_flutter_datagrid: ^20.4.49
  wakelock: ^0.6.2
  fluttertoast: ^8.1.2
  # double_back_to_close_app: ^2.1.0
  # another_tv_remote: ^0.0.1
  # sendkeyboardevent: ^0.1.3
  package_info_plus: ^3.0.2
  cron: ^0.5.1
  # audioplayers: ^3.0.1
  # flutter_volume_controller: ^1.2.3
  # sound_mode: ^2.0.2  
  iso_calendar: ^1.0.0
  const_date_time: ^1.0.2 
  radio_group_v2: ^1.0.2
  device_info_plus: ^8.1.0
  quickalert: ^1.0.1
  flutter_overlay_loader: ^2.0.0 
  loading_indicator: ^3.1.0
  percent_indicator: ^4.2.2 
  network_info_plus: ^3.0.2

dev_dependencies:
  # build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0 
  # ---> flutter pub run change_app_package_name:main com.tivn.app
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  intl: ^0.18.0 
  flutter_launcher_name: ^0.0.1
flutter_launcher_name:
  name: "TIVN-Quang Ngai"
  # ----> flutter pub run flutter_launcher_name:main
  icons_launcher: ^2.0.6
icons_launcher:
  image_path: 'D:\Programming\Flutter\ShowChart\tivn_chart\assets\ic_launcher.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assetss to your application, add an assets section, like this:
  assets: 
    - assets/vietnam.png 
    - assets/japan.png 
    - assets/logo.png 
    - assets/ic_launcher.png
    - assets/hdvsmm.mp3
    - assets/loading.gif
    - assets/chart.png
    - assets/customer.png
    - assets/size.png
    - assets/color.png
    - assets/style.png 
    - assets/letter-l.png
    - assets/letter-i.png
    - assets/letter-n.png
    - assets/letter-e.png
    - assets/1.png
    - assets/2.png
    - assets/c.png
    - assets/check1.png
    - assets/check2.png
    - assets/add.png
    - assets/minus.png
    - assets/arrow-up.png
    - assets/arrow-down.png
    - assets/error.png
    - assets/warning-yellow.png
    - assets/warning-red.png
  #   - images/a_dot_ham.jpeg

  # An image assets can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assetss-and-images/#resolution-aware

  # For details regarding adding assetss from package dependencies, see
  # https://flutter.dev/assetss-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the assets and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - assets: fonts/Schyler-Regular.ttf
  #       - assets: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - assets: fonts/TrajanPro.ttf
  #       - assets: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
